### ISSUE TITLE
Please provide aarch64 container

### ISSUE THREAD

**Issue by zyga** [christophebedard/dco-check#116]
I'd like to use your container in CI but some of my infrastructure has moved to aarch64. It would be great to support that architecture without having to maintain additional containers.

**Comment by christophebedard** [comment]
Sure, makes sense to provide an arm64 image as well! #118 enables this. Pulling the `:latest` image should now work for arm64: https://hub.docker.com/layers/christophebedard/dco-check/latest/images/sha256-4232350e9abe5f482332711ebdcd497b54ee0e0621c6829422459d8d74579202?context=explore. And then new images will be built for every new tag/release in the future.

If you could just confirm that it works for you (since I don't easily have access to an arm64 machine right now), that would be great!

**Comment by zyga** [comment]
Checking now.

**Comment by zyga** [comment]
It works like a charm, thank you!

Sample job exercising this: https://gitlab.com/zygoon/sysota/-/jobs/1920424750

**Comment by christophebedard** [comment]
Great, thanks for the confirmation!
